### ISSUE TITLE
Simulation for Parallel batteries

### ISSUE THREAD

**Issue by GodfreyXHL** [lionsimbatoolbox/LIONSIMBA#25]
Dear developers,
I would like to know, how to simulate if battery packs are run in parallel？

**Comment by lionsimbatoolbox** [comment]
Hello, thanks for your message.

The only workaround that could be adopted is to increase the overall capacity of the single cell; indeed, when placed in parallel, two cells will have the same voltage, but increased capacity. However, since this would be a workaround, there wouldn't be the simulation of the capacity of each cell, but it would be rather a "lumped" model.
