### ISSUE TITLE
Sundials installed in Octave but the program still shows its not installed

### ISSUE THREAD

**Issue by sameer9406** [lionsimbatoolbox/LIONSIMBA#7]
![lionsimba](https://user-images.githubusercontent.com/50555276/76406679-6c30de00-638a-11ea-8965-9f3736223159.png)

**Comment by pasinger** [comment]
Can anyone provide details on how this issue was resolved? Thanks, Patrick

**Comment by lionsimbatoolbox** [comment]
Hi Patrick,

If I remember correctly, the issue was related with the compilers that the user did not have either installed or properly configured.

As a result, despite calling the install_STB.m script, the numerical solvers were not properly compiled.

In Linux the compiling process is quite straight forward (as most compilers come as part of the regular installations), whereas on Windows platforms is usually trickier.

Is the compilation process providing you the compiled code?
