### ISSUE TITLE
About Faraday Constant Value in Parameters_init.m

### ISSUE THREAD

**Issue by BeautifulBeer** [lionsimbatoolbox/LIONSIMBA#9]
Hi!
I found Faraday constant value what you declared in "Parameters_init.m" is slightly different with original Faraday constant.
From the Wikipedia, 

F = 96485.3321233 C·mol−1.

Reference : https://en.wikipedia.org/wiki/Faraday_constant

and here is from "Parameters_init.m"

%% Universal Constants
% Faraday Constant  [C/mol]
param.F         = 96487;

I think param.F should be 96485..
Is there any reason to set the Faraday constant value with "96487"?

I really appreciate this awesome work!
Thank you in advance,
BeautifulBeer

**Comment by lionsimbatoolbox** [comment]
Hi BeautifulBeer,

thanks for the message.

The value of the Faraday constant uses in LIONSIMBA was taken from [1], as reference for most of the parameters used in the paper.

Consider that the value of the constant got updated over the years due to the re-definition of some fundamental physical quantities. You can check this [here](https://physics.nist.gov/cuu/Constants/index.html) for example. I believe this is the reason for this difference.

In the short term the value can be changed on the spot, however in a future release of LIONSIMBA it'll be updated to the latest version.

Thanks!

[1] Northrop, Paul WC, et al. "Coordinate transformation, orthogonal collocation, model reformulation and simulation of electrochemical-thermal behavior of lithium-ion battery stacks." Journal of The Electrochemical Society 158.12 (2011): A1461.
